schema_version: 1

context:
  version: "0.30"

package:
  name: name
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cirun/cirun-${{ version }}.tar.gz
  sha256: bb4401968fe1fad050ffc5d361c436debe483a6e3ddcd7f6e8066dcd3e750ec1

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - cirun = cirun.main:app

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - hatch
    - hatchling
    - requests
    - rich
    - typer

tests:
  - python:
      imports:
        - cirun
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  summary: Cirun Python Client
  license: MIT
  license_file: LICENSE.txt
  homepage: https://pypi.org/project/cirun/
  repository: https://github.com/aktechlabs/cirun-py

extra:
  recipe-maintainers:
    - aktech
    - aktechlabs-bot
    - cirun-bot

